services:
    cache_tags.invalidator.varnish:
        class: lbarulski\CacheTagsBundle\Invalidator\Varnish
        arguments: ["%cache_tags.varnish.host%", "%cache_tags.varnish.port%", "%cache_tags.varnish.path%", "%cache_tags.varnish.timeout%"]

    cache_tags.invalidator:
        alias: cache_tags.invalidator.varnish

    cache_tags.repository:
        class: lbarulski\CacheTagsBundle\Service\Repository

    cache_tags.response_listener:
        class: lbarulski\CacheTagsBundle\Listener\Response
        arguments: [@cache_tags.repository]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
